Fix missing positional argument
Before this change, if you ran “pre-commit run --all”, then the mypy
pre-commit hook would give you this error:

> jasons_pre_commit_hooks/flake_lock_updater.py:65: error: Missing
> positional argument "ignore_patterns" in call to "paths_in_repo"
> [call-arg]
> Found 1 error in 1 file (checked 7 source files)

This change fixes that error.